port: 8580
cache:
  active: false
  path: 
  maxage: 2160 # in hours, 90 days = 2160

logging:
  level: info

wmss: 
  gebco:
    url: https://geoserver.openseamap.org/geoserver/gwc/service/wms
    layers: gebco2021:gebco_2021
    format: image/png
  osm-terrestris:
    url:  https://ows.terrestris.de/osm/service?
    layers: OSM-WMS
    format: image/png
    version: 1.1.0
    styles: 
